### ISSUE TITLE
add a standardized /api-reference method to api -- like /ping

### ISSUE THREAD

**Issue by jhford** [taskcluster/taskcluster-lib-api#88]

**Comment by djmitche** [comment]
This might be useful for debugging, but the current intent for redeployability is
 * to generate this data from a loader component via utilities in taskcluster-lib-docs in order to support the redeployability build process (avoiding loading the express server and other components); and
 * to make this data available from the tools subcomponent as a replacement for `references.taskcluster.net` and `schemas.taskcluster.net`, something like `$baseUrl/tools/references/$project`
Given that the latter would be the same as what's proposed here (modulo JSON encoding) and per discussion with @jhford, I don't think this is necessary.
